# Generated by Django 5.1.7 on 2025-03-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250327_1449'),
    ]

    operations = [
    ]
