# Generated by Django 4.2.7 on 2025-03-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dashboard name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Dashboard description')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default dashboard for the user')),
                ('layout', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Query name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Query description')),
                ('query_params', models.JSONField(help_text='Query parameters')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this query is visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'saved query',
                'verbose_name_plural': 'saved queries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOGS_COUNT', 'Logs Count'), ('SEVERITY_DISTRIBUTION', 'Severity Distribution'), ('RECENT_LOGS', 'Recent Logs'), ('CLASSIFICATION_DISTRIBUTION', 'Classification Distribution'), ('TIME_SERIES', 'Time Series'), ('TOP_SOURCES', 'Top Sources'), ('SYSTEM_STATUS', 'System Status'), ('CUSTOM_CHART', 'Custom Chart')], help_text='Type of widget', max_length=30)),
                ('title', models.CharField(help_text='Widget title', max_length=100)),
                ('configuration', models.JSONField(default=dict, help_text='Widget configuration')),
                ('position_x', models.PositiveSmallIntegerField(default=0, help_text='Horizontal position (grid column)')),
                ('position_y', models.PositiveSmallIntegerField(default=0, help_text='Vertical position (grid row)')),
                ('width', models.PositiveSmallIntegerField(default=1, help_text='Width in grid units')),
                ('height', models.PositiveSmallIntegerField(default=1, help_text='Height in grid units')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(help_text='Dashboard this widget belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard')),
            ],
            options={
                'verbose_name': 'widget',
                'verbose_name_plural': 'widgets',
                'ordering': ['dashboard', 'position_y', 'position_x'],
            },
        ),
    ]
