# Generated by Django 4.2.7 on 2025-03-26 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquery',
            name='user',
            field=models.ForeignKey(help_text='User who created this saved query', on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(help_text='User who owns this dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedquery',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('user', 'name')},
        ),
    ]
