# Generated by Django 5.1.7 on 2025-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsource',
            options={'ordering': ['-created_at'], 'verbose_name': 'log source', 'verbose_name_plural': 'log sources'},
        ),
        migrations.AddField(
            model_name='logentry',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the log entry', max_length=100),
        ),
        migrations.AddField(
            model_name='logentry',
            name='event_id',
            field=models.CharField(blank=True, help_text='Event ID related to the log entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], help_text='Severity level of the log entry', max_length=20),
        ),
    ]
