# Generated by Django 5.1.7 on 2025-03-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logsource_options_logentry_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsource',
            options={'ordering': ['name'], 'verbose_name': 'log source', 'verbose_name_plural': 'log sources'},
        ),
    ]
